"""
Core data models for sg_coach.

These are the domain types used by the coach policy and evaluation engine.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID


class ProgramType(str, Enum):
    ztprog = "ztprog"
    drill = "drill"
    lesson = "lesson"


class Severity(str, Enum):
    primary = "primary"
    secondary = "secondary"
    info = "info"


class ClaveKind(str, Enum):
    son = "son"
    rumba = "rumba"
    bossa = "bossa"
    none = "none"


@dataclass(frozen=True)
class ProgramRef:
    """Reference to a curriculum program (drill, lesson, ztprog)."""
    type: ProgramType
    name: str
    hash: str  # e.g. "sha256:abc123..."


@dataclass(frozen=True)
class TimingErrorStats:
    """Aggregate timing error statistics."""
    mean: float
    std: float
    max: float


@dataclass(frozen=True)
class SessionTiming:
    """Timing configuration for a session."""
    bpm: int
    grid: int  # 8 or 16
    strict: bool
    late_drop_ms: float
    ghost_vel_max: int
    panic_enabled: bool


@dataclass
class SessionEvents:
    """Event counters for a session."""
    late_drops: int = 0
    panic_triggered: bool = False


@dataclass(frozen=True)
class PerformanceSummary:
    """Summary of session performance metrics."""
    bars_played: int
    notes_expected: int
    notes_played: int
    notes_dropped: int
    timing_error_ms: TimingErrorStats
    error_by_step: Dict[str, float] = field(default_factory=dict)


@dataclass
class SessionRecord:
    """Complete record of a practice session."""
    session_id: UUID
    instrument_id: str
    engine_version: str
    program_ref: ProgramRef
    timing: SessionTiming
    duration_s: float
    performance: PerformanceSummary
    events: SessionEvents = field(default_factory=SessionEvents)

    def model_copy(self, *, update: Optional[Dict[str, Any]] = None) -> SessionRecord:
        """Create a copy with optional field updates (Pydantic-style API)."""
        import copy
        new = copy.copy(self)
        if update:
            for k, v in update.items():
                if k == "events" and isinstance(v, dict):
                    v = SessionEvents(**v)
                object.__setattr__(new, k, v)
        return new


@dataclass(frozen=True)
class FindingEvidence:
    """Evidence supporting a coach finding."""
    metric: Optional[str] = None
    value: Optional[float] = None
    step: Optional[int] = None
    mean_error_ms: Optional[float] = None


@dataclass(frozen=True)
class CoachFinding:
    """A single coach finding with severity and evidence."""
    type: str  # "timing", "consistency", etc.
    severity: Severity
    evidence: FindingEvidence
    interpretation: str


@dataclass(frozen=True)
class FocusRecommendation:
    """Recommended focus area for next practice."""
    concept: str  # "grid_alignment", "timing_foundation", "consistency"
    reason: str


@dataclass(frozen=True)
class CoachEvaluation:
    """Complete coach evaluation of a session."""
    session_id: UUID
    coach_version: str
    findings: List[CoachFinding]
    strengths: List[str]
    weaknesses: List[str]
    focus_recommendation: FocusRecommendation
    confidence: float


@dataclass(frozen=True)
class PracticeAssignment:
    """A practice assignment generated by the coach."""
    assignment_id: UUID
    program_ref: ProgramRef
    target_bpm: int
    duration_minutes: int
    strict_window_ms: Optional[int] = None
    focus_concept: Optional[str] = None
    rationale: Optional[str] = None
